/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salasdereuniones;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class SRMain extends javax.swing.JFrame {

    /**
     * Creates new form SRMain
     */
    public SRMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Borde2 = new javax.swing.JPanel();
        searchbar = new javax.swing.JTextField();
        Volver = new javax.swing.JButton();
        SeleecionarSR = new javax.swing.JTextField();
        Salasddmenu = new javax.swing.JComboBox<>();
        SeleccionarEmp = new javax.swing.JTextField();
        Empleadoddmenu = new javax.swing.JComboBox<>();
        CancelarBTT = new javax.swing.JButton();
        ReservarBTT = new javax.swing.JButton();
        HoraInicioTxt = new javax.swing.JTextField();
        HoraFintxt = new javax.swing.JTextField();
        HoraInicio = new javax.swing.JTextField();
        HoraFin = new javax.swing.JTextField();
        Logo2 = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Borde2.setBackground(new java.awt.Color(0, 102, 153));

        searchbar.setForeground(new java.awt.Color(204, 204, 204));
        searchbar.setText("Buscar");
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });

        Volver.setBackground(new java.awt.Color(0, 102, 153));
        Volver.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        Volver.setText("Volver");
        Volver.setBorder(null);
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Borde2Layout = new javax.swing.GroupLayout(Borde2);
        Borde2.setLayout(Borde2Layout);
        Borde2Layout.setHorizontalGroup(
            Borde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Borde2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        Borde2Layout.setVerticalGroup(
            Borde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Borde2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Borde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Volver))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        SeleecionarSR.setText("Seleccione la Sala de Reuniones:");
        SeleecionarSR.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SeleecionarSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleecionarSRActionPerformed(evt);
            }
        });

        Salasddmenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala-1(5cp)", "Sala-2(10cp)", "Sala-3(15cp)", "Sala-4 (20cp)" }));
        Salasddmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalasddmenuActionPerformed(evt);
            }
        });

        SeleccionarEmp.setText("Seleccione el Empleado: ");
        SeleccionarEmp.setBorder(null);
        SeleccionarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarEmpActionPerformed(evt);
            }
        });

        Empleadoddmenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Angelica S", "Luis R", "Mariane S", "Gennesis D" }));

        CancelarBTT.setBackground(new java.awt.Color(194, 217, 239));
        CancelarBTT.setText("Cancelar");
        CancelarBTT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CancelarBTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarBTTMouseClicked(evt);
            }
        });
        CancelarBTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBTTActionPerformed(evt);
            }
        });

        ReservarBTT.setBackground(new java.awt.Color(194, 218, 241));
        ReservarBTT.setText("Reservar");
        ReservarBTT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReservarBTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservarBTTMouseClicked(evt);
            }
        });
        ReservarBTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarBTTActionPerformed(evt);
            }
        });

        HoraInicioTxt.setText("Hora de Inicio:");
        HoraInicioTxt.setBorder(null);

        HoraFintxt.setText("Hora de Fin:");
        HoraFintxt.setBorder(null);

        HoraInicio.setForeground(new java.awt.Color(204, 204, 204));
        HoraInicio.setText("hh:mm");
        HoraInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HoraInicioMousePressed(evt);
            }
        });

        HoraFin.setForeground(new java.awt.Color(204, 204, 204));
        HoraFin.setText("hh:mm");
        HoraFin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HoraFinMousePressed(evt);
            }
        });

        Logo2.setEditable(false);
        Logo2.setBackground(new java.awt.Color(255, 255, 255));
        Logo2.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        Logo2.setText("I N T E L ");
        Logo2.setBorder(null);
        Logo2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Logo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Borde2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SeleecionarSR, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Salasddmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SeleccionarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HoraInicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HoraFintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(HoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE))
                                    .addComponent(Empleadoddmenu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(CancelarBTT, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(ReservarBTT, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Borde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Logo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SeleecionarSR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Salasddmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SeleccionarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Empleadoddmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HoraInicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HoraFintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(71, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReservarBTT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CancelarBTT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Logo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logo2ActionPerformed
      Logo2.setEditable(false);
      Logo2.setCaretColor(new java.awt.Color(0, 0, 0, 0));
    }//GEN-LAST:event_Logo2ActionPerformed

    private void SalasddmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalasddmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalasddmenuActionPerformed

    private void SeleccionarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionarEmpActionPerformed

    private void SeleecionarSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleecionarSRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleecionarSRActionPerformed

    private void HoraInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoraInicioMousePressed
        if(HoraInicio.getText().equals("hh:mm")){
        HoraInicio.setText("");
        HoraInicio.setForeground(Color.BLACK);
            
        }
        if(String.valueOf(HoraFin.getText()).isEmpty()){
        HoraFin.setText("hh:mm");
        HoraFin.setForeground(Color.GRAY);
        }
        
        
        
    }//GEN-LAST:event_HoraInicioMousePressed

    private void HoraFinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoraFinMousePressed
       if(String.valueOf(HoraFin.getText()).equals("hh:mm")){
        HoraFin.setText("");
        HoraFin.setForeground(Color.BLACK);
        
    }
       if(HoraInicio.getText().isEmpty()){
        HoraInicio.setText("hh:mm");
        HoraInicio.setForeground(Color.GRAY);
       }
        
        
        
        
    }//GEN-LAST:event_HoraFinMousePressed

    private void ReservarBTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservarBTTMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this, "\nSala:\n" + Salasddmenu.getSelectedItem() + "\nReservada por:\n" + Empleadoddmenu.getSelectedItem() + 
                                                        "\nHora Inicio: " + HoraInicio.getText() + "\nHora Fin:" + HoraFin.getText());
        System.exit(0);
    }//GEN-LAST:event_ReservarBTTMouseClicked

    private void CancelarBTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarBTTMouseClicked
     int opcion = JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas cancelar?", "Confirmar Cancelación", JOptionPane.YES_NO_OPTION);
     
if (opcion == JOptionPane.YES_OPTION) {
   
    System.out.println("Se canceló la acción.");
    
} else {
    System.out.println("La acción no fue cancelada.");
}
    }//GEN-LAST:event_CancelarBTTMouseClicked

    private void ReservarBTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarBTTActionPerformed
       
    }//GEN-LAST:event_ReservarBTTActionPerformed

    private void CancelarBTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarBTTActionPerformed

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbarActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
      
     
        
        
        Inicio anterior = new Inicio();
        anterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SRMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SRMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SRMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SRMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SRMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Borde2;
    private javax.swing.JButton CancelarBTT;
    private javax.swing.JComboBox<String> Empleadoddmenu;
    private javax.swing.JTextField HoraFin;
    private javax.swing.JTextField HoraFintxt;
    private javax.swing.JTextField HoraInicio;
    private javax.swing.JTextField HoraInicioTxt;
    private javax.swing.JTextField Logo2;
    private javax.swing.JButton ReservarBTT;
    private javax.swing.JComboBox<String> Salasddmenu;
    private javax.swing.JTextField SeleccionarEmp;
    private javax.swing.JTextField SeleecionarSR;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField searchbar;
    // End of variables declaration//GEN-END:variables
}
