/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package parqueo;

/**
 *
 * @author porto
 */
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

public class modifyAuditorio extends javax.swing.JPanel {

    /**
     * Creates new form Auditorio
     */
    private Image backgraound_image;
    // Hora de reserva
    private String hourRoom;
    public static Data data = new Data();
    //Fecha
    String fecha = java.time.LocalDate.now().toString();

    public modifyAuditorio(String hourRoom) {
        this.hourRoom = hourRoom;
        initComponents();
        principal.setText("Ingrese el numero de Reserva que quiere eliminar de la hora " + hourRoom + " :");
        setbackgraoundPanel("src/Image/formulario.jpg", panelMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel(){

            @Override
            public void paintComponent(Graphics g) {
                //Obtener dimensiones
                int width = this.getSize().width;
                int height = this.getSize().height;

                if (backgraound_image != null){
                    g.drawImage(backgraound_image, 0, 0, width, height, null);
                }
                super.paintComponent(g);
            }

        };
        principal = new javax.swing.JLabel();
        backBotton = new javax.swing.JButton();
        idInput = new javax.swing.JTextArea();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        reservaBotton = new javax.swing.JButton();
        cautionText = new javax.swing.JLabel();

        panelMenu.setMaximumSize(new java.awt.Dimension(800, 500));
        panelMenu.setMinimumSize(new java.awt.Dimension(800, 500));

        principal.setBackground(new java.awt.Color(255, 255, 255));
        principal.setFont(new java.awt.Font("InaiMathi", 0, 24)); // NOI18N
        principal.setForeground(new java.awt.Color(255, 255, 255));
        principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        principal.setText("*******");

        backBotton.setBackground(new java.awt.Color(153, 0, 0));
        backBotton.setText("Atras");
        backBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBottonActionPerformed(evt);
            }
        });

        idInput.setColumns(20);
        idInput.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        idInput.setRows(5);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reserva:");

        reservaBotton.setBackground(new java.awt.Color(102, 255, 0));
        reservaBotton.setForeground(new java.awt.Color(0, 0, 0));
        reservaBotton.setText("Confirmar");
        reservaBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservaBottonActionPerformed(evt);
            }
        });

        cautionText.setForeground(new java.awt.Color(255, 0, 0));
        cautionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(backBotton))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(reservaBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(cautionText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 52, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addComponent(cautionText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reservaBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(backBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBottonActionPerformed
        // TODO add your handling code here:
        DashAuditorios dashBoard = new DashAuditorios();
        dashBoard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBottonActionPerformed

    private void reservaBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservaBottonActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(idInput.getText());

        if (hourRoom.equals("10 AM")) {
            Historial.deleteHistoialAudiAM(id);
        } else if (hourRoom.equals("3 PM")) {
            Historial.deleteHistoialAudiPM(id);
        }
        DashAuditorios dash = new DashAuditorios();
        dash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_reservaBottonActionPerformed

    //Colocar Backgraound
    public void setbackgraoundPanel(String rutaImage, JPanel panel) {
        panel.setOpaque(false);
        backgraound_image = new ImageIcon(rutaImage).getImage();
        panel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBotton;
    private javax.swing.JLabel cautionText;
    private javax.swing.JTextArea idInput;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JLabel principal;
    private javax.swing.JButton reservaBotton;
    // End of variables declaration//GEN-END:variables
}
