/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package parqueo;

/**
 *
 * @author porto
 */
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

public class Auditorio extends javax.swing.JPanel {

    /**
     * Creates new form Auditorio
     */
    private Image backgraound_image;
    //Hora de reserva
    private String hourRoom;
    public static Data data = new Data();

    public Auditorio(String hourRoom) {
        this.hourRoom = hourRoom;
        initComponents();
        rewritterLabels();
        setbackgraoundPanel("src/Image/auditorioAM.jpg", panelMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel(){

            @Override
            public void paintComponent(Graphics g) {
                //Obtener dimensiones
                int width = this.getSize().width;
                int height = this.getSize().height;

                if (backgraound_image != null){
                    g.drawImage(backgraound_image, 0, 0, width, height, null);
                }
                super.paintComponent(g);
            }

        };
        principal = new javax.swing.JLabel();
        spaceAvailable = new javax.swing.JLabel();
        backBotton = new javax.swing.JButton();
        historialBotton = new javax.swing.JButton();
        reservaBotton = new javax.swing.JButton();
        modifyBotton = new javax.swing.JButton();

        panelMenu.setMaximumSize(new java.awt.Dimension(800, 500));
        panelMenu.setMinimumSize(new java.awt.Dimension(800, 500));

        principal.setBackground(new java.awt.Color(255, 255, 255));
        principal.setFont(new java.awt.Font("InaiMathi", 0, 32)); // NOI18N
        principal.setForeground(new java.awt.Color(255, 255, 255));
        principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        principal.setText("*******");

        spaceAvailable.setBackground(new java.awt.Color(255, 255, 255));
        spaceAvailable.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        spaceAvailable.setForeground(new java.awt.Color(255, 255, 255));
        spaceAvailable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spaceAvailable.setText("##");

        backBotton.setBackground(new java.awt.Color(153, 0, 0));
        backBotton.setText("Atras");
        backBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBottonActionPerformed(evt);
            }
        });

        historialBotton.setBackground(new java.awt.Color(255, 255, 0));
        historialBotton.setForeground(new java.awt.Color(0, 0, 0));
        historialBotton.setText("Historial ");
        historialBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialBottonActionPerformed(evt);
            }
        });

        reservaBotton.setBackground(new java.awt.Color(102, 255, 0));
        reservaBotton.setForeground(new java.awt.Color(0, 0, 0));
        reservaBotton.setText("Reservar");
        reservaBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservaBottonActionPerformed(evt);
            }
        });

        modifyBotton.setBackground(new java.awt.Color(0, 153, 204));
        modifyBotton.setForeground(new java.awt.Color(0, 0, 0));
        modifyBotton.setText("Modificar");
        modifyBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(reservaBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(backBotton)
                .addGap(244, 244, 244)
                .addComponent(modifyBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(historialBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spaceAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(spaceAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(reservaBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historialBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBottonActionPerformed
        // TODO add your handling code here:
        DashAuditorios dashBoard = new DashAuditorios();
        dashBoard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBottonActionPerformed

    private void historialBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialBottonActionPerformed
        if (hourRoom.equals("3 PM"))
            Historial.showHistorialAudiPM();
        else if (hourRoom.equals("10 AM"))
            Historial.showHistorialAudiAM();
    }//GEN-LAST:event_historialBottonActionPerformed

    private void reservaBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservaBottonActionPerformed
        // TODO add your handling code here:
        formularioAuditorio form = new formularioAuditorio(hourRoom);
        form.setSize(800, 500);
        form.setLocation(0, 0);

        panelMenu.removeAll();
        panelMenu.add(form, BorderLayout.CENTER);
        panelMenu.revalidate();
        panelMenu.repaint();  
    }//GEN-LAST:event_reservaBottonActionPerformed

    private void modifyBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBottonActionPerformed
        // TODO add your handling code here:
        modifyAuditorio modify = new modifyAuditorio(hourRoom);
        modify.setSize(800, 500);
        modify.setLocation(0, 0);

        panelMenu.removeAll();
        panelMenu.add(modify, BorderLayout.CENTER);
        panelMenu.revalidate();
        panelMenu.repaint();  
    }//GEN-LAST:event_modifyBottonActionPerformed

    //Colocar Backgraound
    public void setbackgraoundPanel(String rutaImage, JPanel panel) {
        panel.setOpaque(false);
        backgraound_image = new ImageIcon(rutaImage).getImage();
        panel.repaint();
    }

    //Escribir el titulo dependiendo del INPUT
    public void rewritterLabels() {
        int spaceCount = 0;
        principal.setText("Espacios disponibles para el auditorio a las " + hourRoom + " :");

        if (hourRoom.equals("3 PM")) {
            spaceCount = Historial.getCantidadReservasAudiPM();
        } else if (hourRoom.equals("10 AM")) {
            spaceCount = Historial.getCantidadReservasAudiAM();
        }

        spaceAvailable.setText(String.valueOf(spaceCount));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBotton;
    private javax.swing.JButton historialBotton;
    private javax.swing.JButton modifyBotton;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JLabel principal;
    private javax.swing.JButton reservaBotton;
    private javax.swing.JLabel spaceAvailable;
    // End of variables declaration//GEN-END:variables
}
