/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package parqueo;

/**
 *
 * @author porto
 */
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

public class bottonsModify extends javax.swing.JPanel {

    /**
     * Creates new form bottonsModify
     */
    private Image backgraound_image;

    //Importar ubicacion del lugar a modificar
    int rowModify = 0;
    int columModify = 0;
    String parkModify = "";

    public bottonsModify(int rowModify, int columModify, String parkModify) {
        this.parkModify = parkModify;
        this.rowModify = rowModify;
        this.columModify = columModify;
        initComponents();
        setbackgraoundPanel("src/Image/modify.jpg", panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel(){

            @Override
            public void paintComponent(Graphics g) {
                //Obtener dimensiones
                int width = this.getSize().width;
                int height = this.getSize().height;

                if (backgraound_image != null){
                    g.drawImage(backgraound_image, 0, 0, width, height, null);
                }
                super.paintComponent(g);
            }

        };
        Director = new javax.swing.JButton();
        Disponible = new javax.swing.JButton();
        Ocupado = new javax.swing.JButton();
        Discapacitados = new javax.swing.JButton();
        backBotton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(823, 757));
        setMinimumSize(new java.awt.Dimension(823, 757));
        setPreferredSize(new java.awt.Dimension(823, 757));

        Director.setBackground(new java.awt.Color(255, 153, 51));
        Director.setText("Director");
        Director.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectorActionPerformed(evt);
            }
        });

        Disponible.setBackground(new java.awt.Color(102, 255, 51));
        Disponible.setForeground(new java.awt.Color(0, 0, 0));
        Disponible.setText("Disponible");
        Disponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisponibleActionPerformed(evt);
            }
        });

        Ocupado.setBackground(new java.awt.Color(255, 51, 51));
        Ocupado.setText("Ocupado");
        Ocupado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OcupadoActionPerformed(evt);
            }
        });

        Discapacitados.setBackground(new java.awt.Color(0, 153, 255));
        Discapacitados.setText("Discapacitados");
        Discapacitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscapacitadosActionPerformed(evt);
            }
        });

        backBotton1.setBackground(new java.awt.Color(153, 0, 0));
        backBotton1.setText("Atras");
        backBotton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBotton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Director, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Disponible, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Discapacitados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ocupado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(backBotton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(727, Short.MAX_VALUE)))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Disponible, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Discapacitados, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Director, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ocupado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(backBotton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(694, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisponibleActionPerformed
        // TODO add your handling code here:
        Historial.deleteHistoialPark(parkModify + " " + (rowModify + 1) + " " + (columModify + 1));
        modifyPark("O");
        exit();
    }//GEN-LAST:event_DisponibleActionPerformed

    private void backBotton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBotton1ActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_backBotton1ActionPerformed

    private void DiscapacitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscapacitadosActionPerformed
        // TODO add your handling code here:
        Historial.deleteHistoialPark(parkModify + " " + (rowModify + 1) + " " + (columModify + 1));
        modifyPark("E");
        exit();
    }//GEN-LAST:event_DiscapacitadosActionPerformed

    private void DirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectorActionPerformed
        // TODO add your handling code here:
        Historial.deleteHistoialPark(parkModify + " " + (rowModify + 1) + " " + (columModify + 1));
        modifyPark("D");
        exit();
    }//GEN-LAST:event_DirectorActionPerformed

    private void OcupadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OcupadoActionPerformed
        // TODO add your handling code here:
        modifyPark("P");
        exit();
    }//GEN-LAST:event_OcupadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Director;
    private javax.swing.JButton Discapacitados;
    private javax.swing.JButton Disponible;
    private javax.swing.JButton Ocupado;
    private javax.swing.JButton backBotton1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo para volver al dashBoard de parqueos
     */
    private void exit() {
        dashBoardParks parqueo = new dashBoardParks();
        parqueo.setVisible(true);
        this.setVisible(false);
    }

    /**
     * Esta metodo llega a Modificar el lugar seleccionado de la pagina pasada
     *
     * @param status Este es para ver que estado se pondra el parqueo
     */
    private void modifyPark(String status) {
        if (parkModify == "S1") {
            Data.matrizS1[rowModify][columModify] = status;
        } else if (parkModify == "S2") {
            Data.matrizS2[rowModify][columModify] = status;
        } else if (parkModify == "S3") {
            Data.matrizS3[rowModify][columModify] = status;
        }
    }

    public void setbackgraoundPanel(String rutaImage, JPanel panel) {
        panel.setOpaque(false);
        backgraound_image = new ImageIcon(rutaImage).getImage();
        panel.repaint();
    }
}
