/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package parqueo;

/**
 *
 * @author porto
 */
public class bottonsModify extends javax.swing.JPanel {

    /**
     * Creates new form bottonsModify
     */
    int rowModify = 0;
    int columModify = 0;
    String parkModify = "";
    public bottonsModify(int rowModify,int columModify,String parkModify) {
        this.parkModify = parkModify;
        this.rowModify = rowModify;
        this.columModify = columModify;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Director = new javax.swing.JButton();
        Disponible = new javax.swing.JButton();
        Ocupado = new javax.swing.JButton();
        Discapacitados = new javax.swing.JButton();
        backBotton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(823, 757));
        setMinimumSize(new java.awt.Dimension(823, 757));
        setPreferredSize(new java.awt.Dimension(823, 757));

        Director.setBackground(new java.awt.Color(255, 153, 51));
        Director.setText("Director");
        Director.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectorActionPerformed(evt);
            }
        });

        Disponible.setBackground(new java.awt.Color(102, 255, 51));
        Disponible.setForeground(new java.awt.Color(0, 0, 0));
        Disponible.setText("Disponible");
        Disponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisponibleActionPerformed(evt);
            }
        });

        Ocupado.setBackground(new java.awt.Color(255, 51, 51));
        Ocupado.setText("Ocupado");
        Ocupado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OcupadoActionPerformed(evt);
            }
        });

        Discapacitados.setBackground(new java.awt.Color(0, 153, 255));
        Discapacitados.setText("Discapacitados");
        Discapacitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscapacitadosActionPerformed(evt);
            }
        });

        backBotton1.setBackground(new java.awt.Color(153, 0, 0));
        backBotton1.setText("Atras");
        backBotton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBotton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Discapacitados, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ocupado, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Disponible, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Director, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(backBotton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBotton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Disponible, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(Discapacitados, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(Director, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(Ocupado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisponibleActionPerformed
        // TODO add your handling code here:
        modifyPark("O");
        exit();
    }//GEN-LAST:event_DisponibleActionPerformed

    private void backBotton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBotton1ActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_backBotton1ActionPerformed

    private void DiscapacitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscapacitadosActionPerformed
        // TODO add your handling code here:
        modifyPark("E");
        exit();
    }//GEN-LAST:event_DiscapacitadosActionPerformed

    private void DirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectorActionPerformed
        // TODO add your handling code here:
        modifyPark("D");
        exit();
    }//GEN-LAST:event_DirectorActionPerformed

    private void OcupadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OcupadoActionPerformed
        // TODO add your handling code here:
        modifyPark("P");
        exit();
    }//GEN-LAST:event_OcupadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Director;
    private javax.swing.JButton Discapacitados;
    private javax.swing.JButton Disponible;
    private javax.swing.JButton Ocupado;
    private javax.swing.JButton backBotton1;
    // End of variables declaration//GEN-END:variables
    
    //Volver al dashbord
    private void exit(){
        dashBoardParks parqueo = new dashBoardParks();
        parqueo.setVisible(true);
        this.setVisible(false);
    }
    private void modifyPark(String status){
        if(parkModify=="S1") Data.matrizS1[rowModify][columModify] = status;
        else if(parkModify=="S2") Data.matrizS2[rowModify][columModify] = status;
        else if(parkModify=="S3") Data.matrizS3[rowModify][columModify] = status;
    }
}

