/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parqueo;

import java.awt.BorderLayout;

/**
 *
 * @author porto
 */
public class modifyPark extends javax.swing.JFrame {

    /**
     * Creates new form modifyPark
     */
    String parkSelect = "";

    public modifyPark() {
        initComponents();
        confirmBotton.setVisible(false);
        filaComboBox.setVisible(false);
        columComboBox.setVisible(false);
        fila_columna_text.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        backBotton1 = new javax.swing.JButton();
        parkSelector = new javax.swing.JComboBox<>();
        selectBotton = new javax.swing.JButton();
        fila_columna_text = new javax.swing.JLabel();
        Parqueo = new javax.swing.JLabel();
        filaComboBox = new javax.swing.JComboBox<>();
        columComboBox = new javax.swing.JComboBox<>();
        confirmBotton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(906, 826));
        setMinimumSize(new java.awt.Dimension(906, 826));

        panel.setBackground(new java.awt.Color(102, 102, 102));

        backBotton1.setBackground(new java.awt.Color(153, 0, 0));
        backBotton1.setText("Atras");
        backBotton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBotton1ActionPerformed(evt);
            }
        });

        parkSelector.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        parkSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1", "S2", "S3" }));
        parkSelector.setMinimumSize(new java.awt.Dimension(339, 69));
        parkSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parkSelectorActionPerformed(evt);
            }
        });

        selectBotton.setBackground(new java.awt.Color(102, 255, 102));
        selectBotton.setForeground(new java.awt.Color(0, 0, 0));
        selectBotton.setText("Seleccionar");
        selectBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBottonActionPerformed(evt);
            }
        });

        fila_columna_text.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        fila_columna_text.setText("Fila                      Columna");

        Parqueo.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        Parqueo.setText("Parqueo");

        filaComboBox.setMinimumSize(new java.awt.Dimension(96, 63));
        filaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filaComboBoxActionPerformed(evt);
            }
        });

        columComboBox.setMinimumSize(new java.awt.Dimension(96, 63));

        confirmBotton.setBackground(new java.awt.Color(102, 255, 102));
        confirmBotton.setForeground(new java.awt.Color(0, 0, 0));
        confirmBotton.setText("Confirmar");
        confirmBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fila_columna_text, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(filaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(242, 242, 242)
                            .addComponent(columComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(backBotton1))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGap(284, 284, 284)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(selectBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(confirmBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGap(239, 239, 239)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Parqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(parkSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(backBotton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(Parqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parkSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fila_columna_text, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(columComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(362, 362, 362)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(361, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(328, 328, 328)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(329, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBotton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBotton1ActionPerformed
        // TODO add your handling code here:
        dashBoardParks parqueo = new dashBoardParks();
        parqueo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBotton1ActionPerformed

    private void parkSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parkSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parkSelectorActionPerformed

    private void selectBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBottonActionPerformed
        // TODO add your handling code here:
        parkSelect = parkSelector.getSelectedItem().toString();
        Parqueo.setVisible(false);
        parkSelector.setVisible(false);
        fila_columna_text.setVisible(true);
        confirmBotton.setVisible(true);
        filaComboBox.setVisible(true);
        columComboBox.setVisible(true);
        addItemstoBox();
        selectBotton.setVisible(false);
    }//GEN-LAST:event_selectBottonActionPerformed

    private void filaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filaComboBoxActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_filaComboBoxActionPerformed

    private void confirmBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBottonActionPerformed
        // TODO add your handling code here:
        int rowSelector = filaComboBox.getSelectedIndex();
        int columSelector = columComboBox.getSelectedIndex();
        
        bottonsModify panelsModify = new bottonsModify(rowSelector, columSelector, parkSelect);
        panelsModify.setSize(823,757);
        panelsModify.setLocation(0, 0);
        
        panel.removeAll();
        panel.add(panelsModify, BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
                
    }//GEN-LAST:event_confirmBottonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifyPark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifyPark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifyPark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifyPark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modifyPark().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Parqueo;
    private javax.swing.JButton backBotton1;
    private javax.swing.JComboBox<String> columComboBox;
    private javax.swing.JButton confirmBotton;
    private javax.swing.JComboBox<String> filaComboBox;
    private javax.swing.JLabel fila_columna_text;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> parkSelector;
    private javax.swing.JButton selectBotton;
    // End of variables declaration//GEN-END:variables

    private void addItemstoBox() {

        if (parkSelect == "S1") {
            for (int i = 0; i < 5; i++) {
                filaComboBox.addItem(String.valueOf(i + 1));
            }
            for (int i = 0; i < 4; i++) {
                columComboBox.addItem(String.valueOf(i + 1));
            }
        } else if (parkSelect == "S2") {
            for (int i = 0; i < 5; i++) {
                filaComboBox.addItem(String.valueOf(i + 1));
            }
            for (int i = 0; i < 5; i++) {
                columComboBox.addItem(String.valueOf(i + 1));
            }
        } else if (parkSelect == "S3") {
            for (int i = 0; i < 6; i++) {
                filaComboBox.addItem(String.valueOf(i + 1));
            }
            for (int i = 0; i < 5; i++) {
                columComboBox.addItem(String.valueOf(i + 1));
            }
        }
    }
}
