/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package parqueo;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
/**
 *
 * @author porto
 */
public class ParkS2 extends javax.swing.JPanel {

    /**
     * Creates new form ParkS1temp
     */
    private Image backgraound_image;

    public ParkS2() {

        initComponents();
        setMatrizS2();
        setbackgraoundPanel("src/Image/parqueoS2.jpg", panelS2);
    }

// Matriz de Botones
    private int rowS2 = 5; // 5 filas
    private int columS2 = 5; // 5 columnas
    JButton[][] parkS2;

    //metodo para cerrar
    private void cerrarVentana() {
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.dispose(); // Cierra la ventana
        }
    }

// Método para Crear Matriz
    //Parqueo S1 5x4
    public void setMatrizS2() {
        parkS2 = new JButton[rowS2][columS2];
        //Posicion inicial del primer boton
        int positionX = 30;
        int positionY = 30;

        //creacion de botones por coordenadas
        for (int i = 0; i < rowS2; i++) {
            for (int j = 0; j < columS2; j++) {
                parkS2[i][j] = new JButton();
                parkS2[i][j].setBounds(positionX, positionY, 115, 60);
                parkS2[i][j].setBackground(Color.LIGHT_GRAY);
                parkS2[i][j].setText("Loading...");
                ButtonController bt = new ButtonController();
                parkS2[i][j].addActionListener(bt);

                panelS2.add(parkS2[i][j]);
                positionX += 180;
            }
            positionX = 30;
            positionY += 120;
        }

        panelS2.revalidate();
        panelS2.repaint();
        valueBottons(rowS2, columS2, Data.matrizS2); // Llamar sin parámetros
    }

//Declarar la accion de los botones
    private class ButtonController implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            //seleccionar el boton de la matrix
            for (int i = 0; i < rowS2; i++) {
                for (int j = 0; j < columS2; j++) {
                    if (e.getSource().equals(parkS2[i][j])) {
                        if (Data.matrizS2[i][j] == "P") {
                            JOptionPane.showMessageDialog(null, "Elije otro espacio este no esta disponible");
                        } else {
                            formularioRequest form = new formularioRequest();
                            form.setDatoX(i);
                            form.setDatoY(j);
                            form.setStatus(Data.matrizS2[i][j]);
                            form.setidPark("S2");
                            cerrarVentana();
                            form.setVisible(true);
                        }
                    }
                }
            }
        }
    }

// Método para actualizar botones según la disponibilidad
    public void valueBottons(int x, int y, String[][] matrix) {
        for (int i = 0; i < x; i++) {
            for (int j = 0; j < y; j++) {
                if (matrix[i][j] == "O") {
                    parkS2[i][j].setBackground(Color.GREEN);
                    parkS2[i][j].setText("Disponible");
                } else if (matrix[i][j] == "E") {
                    parkS2[i][j].setBackground(Color.BLUE);
                    parkS2[i][j].setText("Disponible");
                } else if (matrix[i][j] == "D") {
                    parkS2[i][j].setBackground(Color.ORANGE);
                    parkS2[i][j].setText("Disponible");
                } else {
                    parkS2[i][j].setBackground(Color.RED);
                    parkS2[i][j].setText("No disponible");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelS2 = new javax.swing.JPanel(){

            @Override
            public void paintComponent(Graphics g) {
                //Obtener dimensiones
                int width = this.getSize().width;
                int height = this.getSize().height;

                if (backgraound_image != null){
                    g.drawImage(backgraound_image, 0, 0, width, height, null);
                }
                super.paintComponent(g);
            }

        };

        setPreferredSize(new java.awt.Dimension(500, 300));

        panelS2.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout panelS2Layout = new javax.swing.GroupLayout(panelS2);
        panelS2.setLayout(panelS2Layout);
        panelS2Layout.setHorizontalGroup(
            panelS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        panelS2Layout.setVerticalGroup(
            panelS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelS2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    //Colocar fondo en el panel
    public void setbackgraoundPanel(String rutaImage, JPanel panel) {
        panel.setOpaque(false);
        backgraound_image = new ImageIcon(rutaImage).getImage();
        panel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelS2;
    // End of variables declaration//GEN-END:variables
}
