/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectospaceadmin;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author porto
 */
public class ParkS3 extends javax.swing.JPanel {

    /**
     * Creates new form ParkS1temp
     */


    public ParkS3() {
        initComponents();
        setMatrizS3();
    }

// Matriz de Botones
    private int rowS3 = 6; // 5 filas
    private int columS3 = 5; // 5 columnas
    JButton[][] parkS3;

    //metodo para cerrar
    private void cerrarVentana() {
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.dispose(); // Cierra la ventana
        }
    }

// Método para Crear Matriz
    //Parqueo S1 5x4
    public void setMatrizS3() {
        parkS3 = new JButton[rowS3][columS3];
        int positionX = 30;
        int positionY = 30;

        for (int i = 0; i < rowS3; i++) {
            for (int j = 0; j < columS3; j++) {
                parkS3[i][j] = new JButton();
                parkS3[i][j].setBounds(positionX, positionY, 115, 60);
                parkS3[i][j].setBackground(Color.LIGHT_GRAY);
                parkS3[i][j].setText("Loading...");
                ButtonController bt = new ButtonController();
                parkS3[i][j].addActionListener(bt);

                panelS3.add(parkS3[i][j]);
                positionX += 180;
            }
            positionX = 30;
            positionY += 100;
        }

        panelS3.revalidate();
        panelS3.repaint();
        valueBottons(rowS3, columS3, Data.matrizS3); // Llamar sin parámetros
    }

    //Clase de accion de boton 
    private class ButtonController implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            //seleccionar el boton de la matrix
            for (int i = 0; i < rowS3; i++) {
                for (int j = 0; j < columS3; j++) {
                    if (e.getSource().equals(parkS3[i][j])) {
                        if (Data.matrizS3[i][j] == "P") {
                            JOptionPane.showMessageDialog(null, "Elije otro espacio este no esta disponible");
                        } else {
                            formularioRequest form = new formularioRequest();
                            form.setDatoX(i);
                            form.setDatoY(j);
                            form.setStatus(Data.matrizS3[i][j]);
                            form.setidPark("S3");
                            cerrarVentana();
                            form.setVisible(true);
                        }
                    }
                }
            }
        }

    }

// Método para actualizar botones según la disponibilidad
    public void valueBottons(int x, int y, String[][] matrix) {
        for (int i = 0; i < x; i++) {
            for (int j = 0; j < y; j++) {
                if (matrix[i][j] == "O") {
                    parkS3[i][j].setBackground(Color.GREEN);
                    parkS3[i][j].setText("Disponible");
                } else if (matrix[i][j] == "E") {
                    parkS3[i][j].setBackground(Color.BLUE);
                    parkS3[i][j].setText("Disponible");
                } else if (matrix[i][j] == "D") {
                    parkS3[i][j].setBackground(Color.ORANGE);
                    parkS3[i][j].setText("Disponible");
                } else {
                    parkS3[i][j].setBackground(Color.RED);
                    parkS3[i][j].setText("No disponible");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelS3 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(500, 300));

        panelS3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout panelS3Layout = new javax.swing.GroupLayout(panelS3);
        panelS3.setLayout(panelS3Layout);
        panelS3Layout.setHorizontalGroup(
            panelS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        panelS3Layout.setVerticalGroup(
            panelS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelS3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelS3;
    // End of variables declaration//GEN-END:variables
}
