/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cubiculo;

/**
 *
 * @author genni
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        ReservasButton = new javax.swing.JButton();
        ModificarButton = new javax.swing.JButton();
        DisponibilidadButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        BIENVENIDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setForeground(new java.awt.Color(255, 153, 153));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReservasButton.setBackground(new java.awt.Color(255, 102, 102));
        ReservasButton.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        ReservasButton.setLabel("Reservar Cubículos");
        Panel1.add(ReservasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 220, 60));

        ModificarButton.setBackground(new java.awt.Color(255, 102, 102));
        ModificarButton.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        ModificarButton.setText("Modificar cubículos");
        Panel1.add(ModificarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 220, 60));

        DisponibilidadButton.setBackground(new java.awt.Color(255, 102, 102));
        DisponibilidadButton.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        DisponibilidadButton.setText("Ver Disponibilidad");
        Panel1.add(DisponibilidadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 220, 60));

        SalirButton.setBackground(new java.awt.Color(204, 0, 0));
        SalirButton.setForeground(new java.awt.Color(255, 255, 255));
        SalirButton.setText("Salir");
        Panel1.add(SalirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        BIENVENIDO.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        BIENVENIDO.setText("¡BIENVENIDO!");
        Panel1.add(BIENVENIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BIENVENIDO;
    private javax.swing.JButton DisponibilidadButton;
    private javax.swing.JButton ModificarButton;
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton ReservasButton;
    private javax.swing.JButton SalirButton;
    // End of variables declaration//GEN-END:variables
}
