/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectospaceadmin;

import java.awt.BorderLayout;

/**
 *
 * @author porto
 */
public class dashBoardParks extends javax.swing.JFrame {

    /**
     * Este JFrame es para poder reservar los espacios del parqueo y ver que
     * tipo de parqueo
     */
    private Empleado[] arrEmpleado;
    private String[][] matrizS1;
    private String[][] matrizS2;
    private String[][] matrizS3;

    public dashBoardParks(Empleado[] arrEmpleado, String[][] matrizS1, String[][] matrizS2, String[][] matrizS3) {
        this.arrEmpleado = arrEmpleado;
        this.matrizS1 = matrizS1;
        this.matrizS2 = matrizS2;
        this.matrizS3 = matrizS3;
        initComponents();
    }
//
//    public static boolean idVerificator(int id) {
//        
//        for (int i = 0; i < arrEmpleado.length; i++) {
//            if (arrEmpleado[i] != null && arrEmpleado[i].getId() == id) { // si el empleado seleccionado no es NULL y Es igual ID retorna el empleado seleccionado
//                return true;
//            }
//        }
//        return false;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        parkBttnS1 = new javax.swing.JButton();
        parkBttnS2 = new javax.swing.JButton();
        parkBttnS3 = new javax.swing.JButton();
        contentPark = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        parkBttnS1.setBackground(new java.awt.Color(51, 51, 51));
        parkBttnS1.setText("Parqueo S1");
        parkBttnS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parkBttnS1ActionPerformed(evt);
            }
        });

        parkBttnS2.setBackground(new java.awt.Color(51, 51, 51));
        parkBttnS2.setText("Parqueo S2");
        parkBttnS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parkBttnS2ActionPerformed(evt);
            }
        });

        parkBttnS3.setBackground(new java.awt.Color(51, 51, 51));
        parkBttnS3.setText("Parqueo S3");
        parkBttnS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parkBttnS3ActionPerformed(evt);
            }
        });

        contentPark.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout contentParkLayout = new javax.swing.GroupLayout(contentPark);
        contentPark.setLayout(contentParkLayout);
        contentParkLayout.setHorizontalGroup(
            contentParkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentParkLayout.setVerticalGroup(
            contentParkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(parkBttnS1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(parkBttnS2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(parkBttnS3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(contentPark, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parkBttnS1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parkBttnS2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parkBttnS3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parkBttnS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parkBttnS3ActionPerformed
        ParkS3 parkS3 = new ParkS3(arrEmpleado,matrizS1,matrizS2,matrizS3);
        parkS3.setSize(900, 658);
        parkS3.setLocation(0, 0);

        contentPark.removeAll();
        contentPark.add(parkS3, BorderLayout.CENTER);
        contentPark.revalidate();
        contentPark.repaint();
    }//GEN-LAST:event_parkBttnS3ActionPerformed

    private void parkBttnS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parkBttnS1ActionPerformed
        ParkS1 parkS1 = new ParkS1(arrEmpleado,matrizS1,matrizS2,matrizS3);
        parkS1.setSize(900, 658);
        parkS1.setLocation(0, 0);

        contentPark.removeAll();
        contentPark.add(parkS1, BorderLayout.CENTER);
        contentPark.revalidate();
        contentPark.repaint();
    }//GEN-LAST:event_parkBttnS1ActionPerformed

    private void parkBttnS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parkBttnS2ActionPerformed
        ParkS2 parkS2 = new ParkS2(arrEmpleado,matrizS1,matrizS2,matrizS3);
        parkS2.setSize(900, 658);
        parkS2.setLocation(0, 0);

        contentPark.removeAll();
        contentPark.add(parkS2, BorderLayout.CENTER);
        contentPark.revalidate();
        contentPark.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_parkBttnS2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashBoardParks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashBoardParks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashBoardParks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashBoardParks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPark;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton parkBttnS1;
    private javax.swing.JButton parkBttnS2;
    private javax.swing.JButton parkBttnS3;
    // End of variables declaration//GEN-END:variables
}
