/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectospaceadmin;

import javax.swing.JOptionPane;

/**
 *
 * @author porto
 */
public class Park_s1 extends javax.swing.JFrame {

    boolean star_up[][] = {{true, false, false},
    {false, false, true},
    {true, true, true}};


    /**
     * Creates new form Park_c1
     */
    public Park_s1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        space1_2 = new javax.swing.JButton();
        space1_0 = new javax.swing.JButton();
        space1_1 = new javax.swing.JButton();
        space1_5 = new javax.swing.JButton();
        space1_3 = new javax.swing.JButton();
        space1_4 = new javax.swing.JButton();
        space1_8 = new javax.swing.JButton();
        space1_6 = new javax.swing.JButton();
        space1_7 = new javax.swing.JButton();
        S1_titule = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        space1_2.setBackground(new java.awt.Color(0, 153, 0));
        space1_2.setText("jButton1");
        if(star_up[0][2]==false){
            space1_2.setBackground(new java.awt.Color(136, 8, 8));
            space1_2.setText("No Disponible");
        }
        else{
            space1_2.setBackground(new java.awt.Color(0, 153, 0));
            space1_2.setText("Disponible");
        }
        space1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space1_2ActionPerformed(evt);
            }
        });

        space1_0.setBackground(new java.awt.Color(0, 153, 0));
        space1_0.setText("jButton1");
        if(star_up[0][0]==false){
            space1_0.setBackground(new java.awt.Color(136, 8, 8));
            space1_0.setText("No Disponible");
        }
        else{
            space1_0.setBackground(new java.awt.Color(0, 153, 0));
            space1_0.setText("Disponible");
        }
        space1_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space1_0ActionPerformed(evt);
            }
        });

        space1_1.setBackground(new java.awt.Color(0, 153, 0));
        space1_1.setText("jButton1");
        if(star_up[0][1]==false){
            space1_1.setBackground(new java.awt.Color(136, 8, 8));
            space1_1.setText("No Disponible");
        }
        else{
            space1_1.setBackground(new java.awt.Color(0, 153, 0));
            space1_1.setText("Disponible");
        }

        space1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space1_1ActionPerformed(evt);
            }
        });

        space1_5.setBackground(new java.awt.Color(0, 153, 0));
        space1_5.setText("jButton1");
        if(star_up[1][2]==false){
            space1_5.setBackground(new java.awt.Color(136, 8, 8));
            space1_5.setText("No Disponible");
        }
        else{
            space1_5.setBackground(new java.awt.Color(0, 153, 0));
            space1_5.setText("Disponible");
        }
        space1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space1_5ActionPerformed(evt);
            }
        });

        space1_3.setBackground(new java.awt.Color(0, 153, 0));
        space1_3.setText("jButton1");
        if(star_up[1][0]==false){
            space1_3.setBackground(new java.awt.Color(136, 8, 8));
            space1_3.setText("No Disponible");
        }
        else{
            space1_3.setBackground(new java.awt.Color(0, 153, 0));
            space1_3.setText("Disponible");
        }
        space1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space1_3ActionPerformed(evt);
            }
        });

        space1_4.setBackground(new java.awt.Color(0, 153, 0));
        space1_4.setText("jButton1");
        if(star_up[1][1]==false){
            space1_4.setBackground(new java.awt.Color(136, 8, 8));
            space1_4.setText("No Disponible");
        }
        else{
            space1_4.setBackground(new java.awt.Color(0, 153, 0));
            space1_4.setText("Disponible");
        }
        space1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space1_4ActionPerformed(evt);
            }
        });

        space1_8.setBackground(new java.awt.Color(0, 153, 0));
        space1_8.setText("jButton1");
        if(star_up[2][2]==false){
            space1_8.setBackground(new java.awt.Color(136, 8, 8));
            space1_8.setText("No Disponible");
        }
        else{
            space1_8.setBackground(new java.awt.Color(0, 153, 0));
            space1_8.setText("Disponible");
        }
        space1_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space1_8ActionPerformed(evt);
            }
        });

        space1_6.setBackground(new java.awt.Color(0, 153, 0));
        space1_6.setText("jButton1");
        if(star_up[2][0]==false){
            space1_6.setBackground(new java.awt.Color(136, 8, 8));
            space1_6.setText("No Disponible");
        }
        else{
            space1_6.setBackground(new java.awt.Color(0, 153, 0));
            space1_6.setText("Disponible");
        }
        space1_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space1_6ActionPerformed(evt);
            }
        });

        space1_7.setBackground(new java.awt.Color(0, 153, 0));
        space1_7.setText("jButton1");
        if(star_up[2][1]==false){
            space1_7.setBackground(new java.awt.Color(136, 8, 8));
            space1_7.setText("No Disponible");
        }
        else{
            space1_7.setBackground(new java.awt.Color(0, 153, 0));
            space1_7.setText("Disponible");
        }
        space1_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                space1_7ActionPerformed(evt);
            }
        });

        S1_titule.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        S1_titule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        S1_titule.setText("Park S1");
        S1_titule.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(S1_titule, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(307, 307, 307))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(space1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(space1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(space1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(space1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(space1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(space1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(space1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(space1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(space1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(149, 149, 149))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(S1_titule, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(space1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(space1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(space1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Codigo de cada boton 
    private void space1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space1_2ActionPerformed
        if (star_up[0][2] == false) {
            JOptionPane.showMessageDialog(null, "No disponible");
        }
    }//GEN-LAST:event_space1_2ActionPerformed

    private void space1_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space1_0ActionPerformed
        if (star_up[0][0] == false) {
            JOptionPane.showMessageDialog(null, "No disponible");
        }
    }//GEN-LAST:event_space1_0ActionPerformed

    private void space1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space1_1ActionPerformed
        if (star_up[0][1] == false) {
            JOptionPane.showMessageDialog(null, "No disponible");
        }     }//GEN-LAST:event_space1_1ActionPerformed

    private void space1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space1_5ActionPerformed
        if (star_up[1][2] == false) {
            JOptionPane.showMessageDialog(null, "No disponible");
        }     }//GEN-LAST:event_space1_5ActionPerformed

    private void space1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space1_3ActionPerformed
        if (star_up[1][0] == false) {
            JOptionPane.showMessageDialog(null, "No disponible");
        }     }//GEN-LAST:event_space1_3ActionPerformed

    private void space1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space1_4ActionPerformed
        if (star_up[1][1] == false) {
            JOptionPane.showMessageDialog(null, "No disponible");
        }     }//GEN-LAST:event_space1_4ActionPerformed

    private void space1_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space1_8ActionPerformed
        if (star_up[2][2] == false) {
            JOptionPane.showMessageDialog(null, "No disponible");
        }     }//GEN-LAST:event_space1_8ActionPerformed

    private void space1_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space1_6ActionPerformed
        if (star_up[2][0] == false) {
            JOptionPane.showMessageDialog(null, "No disponible");
        }     }//GEN-LAST:event_space1_6ActionPerformed

    private void space1_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_space1_7ActionPerformed
        if (star_up[2][1] == false) {
            JOptionPane.showMessageDialog(null, "No disponible");
        }     }//GEN-LAST:event_space1_7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Park_s1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Park_s1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Park_s1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Park_s1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Park_s1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel S1_titule;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton space1_0;
    private javax.swing.JButton space1_1;
    private javax.swing.JButton space1_2;
    private javax.swing.JButton space1_3;
    private javax.swing.JButton space1_4;
    private javax.swing.JButton space1_5;
    private javax.swing.JButton space1_6;
    private javax.swing.JButton space1_7;
    private javax.swing.JButton space1_8;
    // End of variables declaration//GEN-END:variables

}
