/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parqueo;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author porto
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private Image backgraound_image;

    public Menu() {
        initComponents();
        setbackgraoundPanel("src/Image/backgraound_image.jpg", panelMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel(){

            @Override
            public void paintComponent(Graphics g) {
                //Obtener dimensiones
                int width = this.getSize().width;
                int height = this.getSize().height;

                if (backgraound_image != null){
                    g.drawImage(backgraound_image, 0, 0, width, height, null);
                }
                super.paintComponent(g);
            }

        };
        cubiculoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        recreativaButton = new javax.swing.JButton();
        parkButton = new javax.swing.JButton();
        auditorioButton = new javax.swing.JButton();
        reunionesButton1 = new javax.swing.JButton();
        backBotton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));

        panelMenu.setMaximumSize(new java.awt.Dimension(800, 500));
        panelMenu.setMinimumSize(new java.awt.Dimension(800, 500));

        cubiculoButton.setBackground(new java.awt.Color(204, 204, 204));
        cubiculoButton.setText("Cubiculos");
        cubiculoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubiculoButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("InaiMathi", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenidos al sistema");

        recreativaButton.setBackground(new java.awt.Color(204, 204, 204));
        recreativaButton.setText("Zonas recreativas");
        recreativaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recreativaButtonActionPerformed(evt);
            }
        });

        parkButton.setBackground(new java.awt.Color(204, 204, 204));
        parkButton.setText("Parqueos");
        parkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parkButtonActionPerformed(evt);
            }
        });

        auditorioButton.setBackground(new java.awt.Color(204, 204, 204));
        auditorioButton.setText("Auditorio");
        auditorioButton.setToolTipText("");
        auditorioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditorioButtonActionPerformed(evt);
            }
        });

        reunionesButton1.setBackground(new java.awt.Color(204, 204, 204));
        reunionesButton1.setText("Sala de reuniones");
        reunionesButton1.setToolTipText("");
        reunionesButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reunionesButton1ActionPerformed(evt);
            }
        });

        backBotton6.setBackground(new java.awt.Color(153, 0, 0));
        backBotton6.setText("Salir");
        backBotton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBotton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auditorioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recreativaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cubiculoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(331, Short.MAX_VALUE)
                .addComponent(reunionesButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(backBotton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(243, 243, 243))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(backBotton6)))
                .addGap(73, 73, 73)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cubiculoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(reunionesButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recreativaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auditorioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cubiculoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubiculoButtonActionPerformed
        Form ventana = new Form();
        ventana.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_cubiculoButtonActionPerformed

    private void recreativaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recreativaButtonActionPerformed
        // TODO add your handling code here:
        EspaciosRecreativos ventana = new EspaciosRecreativos();
        ventana.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_recreativaButtonActionPerformed

    private void parkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parkButtonActionPerformed
        // TODO add your handling code here:
        dashBoardParks dashBoardMenu = new dashBoardParks();
        dashBoardMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_parkButtonActionPerformed

    private void auditorioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditorioButtonActionPerformed
        // TODO add your handling code here:
        DashAuditorios dashBoardMenu = new DashAuditorios();
        dashBoardMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_auditorioButtonActionPerformed

    private void reunionesButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reunionesButton1ActionPerformed
        // TODO add your handling code here:
        SRMain Inicio1 = new SRMain();
        Inicio1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_reunionesButton1ActionPerformed

    private void backBotton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBotton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backBotton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    //Colocar una imagen como fondo
    public void setbackgraoundPanel(String rutaImage, JPanel panel) {
        panel.setOpaque(false);
        backgraound_image = new ImageIcon(rutaImage).getImage();
        panel.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton auditorioButton;
    private javax.swing.JButton backBotton6;
    private javax.swing.JButton cubiculoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JButton parkButton;
    private javax.swing.JButton recreativaButton;
    private javax.swing.JButton reunionesButton1;
    // End of variables declaration//GEN-END:variables
}
