/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parqueo;

import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class ModReservaSR extends javax.swing.JFrame {

    /**
     * Creates new form ModReserva
     */
    private SRMain mainReference;
    public ModReservaSR(SRMain main) {
        initComponents();
        this.mainReference = main;
 
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkgroundMod = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Volver2 = new javax.swing.JButton();
        searchbar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        SalaaModificarBTT = new javax.swing.JTextField();
        ingresarsalaMod = new javax.swing.JTextField();
        ingresarsalaMod1 = new javax.swing.JTextField();
        EmpIDModBTT = new javax.swing.JTextField();
        HoraInicioTXT = new javax.swing.JTextField();
        HoraIncioBTT = new javax.swing.JTextField();
        HoraFinTXT = new javax.swing.JTextField();
        HoraFinBTT = new javax.swing.JTextField();
        edificioJPG = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ModificarBTT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bkgroundMod.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        Volver2.setBackground(new java.awt.Color(153, 0, 0));
        Volver2.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        Volver2.setForeground(new java.awt.Color(255, 255, 255));
        Volver2.setText("Volver");
        Volver2.setBorder(null);
        Volver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver2ActionPerformed(evt);
            }
        });

        searchbar.setForeground(new java.awt.Color(204, 204, 204));
        searchbar.setText("Buscar");
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Volver2)
                .addGap(276, 276, 276)
                .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volver2)
                    .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        ingresarsalaMod.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ingresarsalaMod.setText("Ingrese la Sala que desea modificar:");
        ingresarsalaMod.setBorder(null);
        ingresarsalaMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarsalaModActionPerformed(evt);
            }
        });

        ingresarsalaMod1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ingresarsalaMod1.setText("Ingrese el ID del Empleado:");
        ingresarsalaMod1.setBorder(null);
        ingresarsalaMod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarsalaMod1ActionPerformed(evt);
            }
        });

        HoraInicioTXT.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        HoraInicioTXT.setText("Hora de Inicio:");
        HoraInicioTXT.setBorder(null);
        HoraInicioTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraInicioTXTActionPerformed(evt);
            }
        });

        HoraFinTXT.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        HoraFinTXT.setText("Hora de Fin:");
        HoraFinTXT.setBorder(null);
        HoraFinTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraFinTXTActionPerformed(evt);
            }
        });

        edificioJPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/imagen edifico.png"))); // NOI18N

        jTextField1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jTextField1.setText("I N T E L");
        jTextField1.setBorder(null);

        ModificarBTT.setBackground(new java.awt.Color(221, 89, 89));
        ModificarBTT.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        ModificarBTT.setForeground(new java.awt.Color(255, 255, 255));
        ModificarBTT.setText("Modificar");
        ModificarBTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBTTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bkgroundModLayout = new javax.swing.GroupLayout(bkgroundMod);
        bkgroundMod.setLayout(bkgroundModLayout);
        bkgroundModLayout.setHorizontalGroup(
            bkgroundModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bkgroundModLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bkgroundModLayout.createSequentialGroup()
                .addGroup(bkgroundModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ModificarBTT)
                    .addGroup(bkgroundModLayout.createSequentialGroup()
                        .addGroup(bkgroundModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bkgroundModLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(bkgroundModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ingresarsalaMod1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HoraFinTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HoraInicioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bkgroundModLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ingresarsalaMod, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addGroup(bkgroundModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SalaaModificarBTT, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpIDModBTT, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoraIncioBTT, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoraFinBTT, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(edificioJPG)
                .addGap(76, 76, 76))
        );
        bkgroundModLayout.setVerticalGroup(
            bkgroundModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgroundModLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bkgroundModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bkgroundModLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(bkgroundModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ingresarsalaMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SalaaModificarBTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(bkgroundModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ingresarsalaMod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpIDModBTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(bkgroundModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HoraInicioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoraIncioBTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(bkgroundModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HoraFinTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoraFinBTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bkgroundModLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(edificioJPG)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(ModificarBTT)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkgroundMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkgroundMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Volver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver2ActionPerformed

        mainReference.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Volver2ActionPerformed

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbarActionPerformed

    private void ingresarsalaModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarsalaModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarsalaModActionPerformed

    private void ingresarsalaMod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarsalaMod1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarsalaMod1ActionPerformed

    private void HoraInicioTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraInicioTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraInicioTXTActionPerformed

    private void HoraFinTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraFinTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraFinTXTActionPerformed

    private void ModificarBTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBTTActionPerformed
    String salaNumero = SalaaModificarBTT.getText();
    String empID = EmpIDModBTT.getText();
    String nuevaHoraInicio = HoraIncioBTT.getText();
    String nuevaHoraFin = HoraFinBTT.getText();
    
    //Valida campos vacios
    if (salaNumero.isEmpty() || empID.isEmpty() || 
        nuevaHoraInicio.isEmpty() || nuevaHoraFin.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Por favor complete todos los campos",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    //Busca la sala
    SalaReuniones salaModificar = null;
    for (SalaReuniones sala : mainReference.getSalas()) {
        if (sala.getNumerosala().equals(salaNumero)) {
            salaModificar = sala;
            break;
        }
    }
    
    //Validar
    if(salaModificar == null){
        JOptionPane.showMessageDialog(null, "No se encontró la sala especificada",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        
        return;
    }
    
    if(!salaModificar.isOcupada()){
        JOptionPane.showMessageDialog(null,"La sala no tiene una reserva activa",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    //Modificar
    
    boolean modificacionExitosa = salaModificar.modificarReserva(nuevaHoraInicio, nuevaHoraFin);
    
    if (modificacionExitosa) {
        JOptionPane.showMessageDialog(this,
            "Reserva modificada exitosamente\n" +
            "Sala: " + salaNumero + "\n" +
            "Nueva hora inicio: " + nuevaHoraInicio + "\n" +
            "Nueva hora fin: " + nuevaHoraFin);
            
        // Limpiar campos
        SalaaModificarBTT.setText("");
        EmpIDModBTT.setText("");
        HoraIncioBTT.setText("");
        HoraFinBTT.setText("");
    } else {
        JOptionPane.showMessageDialog(this,
            "No se pudo modificar la reserva. Horario no disponible.",
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }

        
        
        
        
    }//GEN-LAST:event_ModificarBTTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModReservaSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModReservaSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModReservaSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModReservaSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmpIDModBTT;
    private javax.swing.JTextField HoraFinBTT;
    private javax.swing.JTextField HoraFinTXT;
    private javax.swing.JTextField HoraIncioBTT;
    private javax.swing.JTextField HoraInicioTXT;
    private javax.swing.JButton ModificarBTT;
    private javax.swing.JTextField SalaaModificarBTT;
    private javax.swing.JButton Volver2;
    private javax.swing.JPanel bkgroundMod;
    private javax.swing.JLabel edificioJPG;
    private javax.swing.JTextField ingresarsalaMod;
    private javax.swing.JTextField ingresarsalaMod1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField searchbar;
    // End of variables declaration//GEN-END:variables
}
