/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parqueo;

import java.awt.Color;
import javax.swing.JOptionPane;
import static parqueo.Data.arrEmpleado;

/**
 *
 * @author Hp
 */
public class SRMain extends javax.swing.JFrame {

    public static SalaReuniones[] getSalas() {
        return salas;
    }

    public void setSalas(SalaReuniones[] salas) {
        this.salas = salas;
    }

    /**
     * Creates new form SRMain
     */
    private static SalaReuniones[] salas;
    private Empleado[] listaEmpleados = new Empleado[10];
    Empleado test = new Empleado("Erick", "Portocarrero", 118180881, true, false);
    
    public void iniciarEmpleados() {
        //Tabla de empleados
        listaEmpleados[0] = new Empleado("Erick", "Portocarrero", 118180881, true, false);
        listaEmpleados[1] = new Empleado("Andres", "Viquez", 12345678, false, true);
        listaEmpleados[2] = new Empleado("Kristel", "Vargas", 208460639, false, false);
        listaEmpleados[3] = new Empleado("David", "Moreno", 98765432, true, true);
        listaEmpleados[4] = new Empleado("Jose", "Apestegui", 118180800, false, false);
        listaEmpleados[5] = new Empleado("Carlos", "Pérez", 1, false, false);
        listaEmpleados[6] = new Empleado("Ana", "García", 2, false, false);
        listaEmpleados[7] = new Empleado("Luis", "Ramírez", 3, false, false);
        listaEmpleados[8] = new Empleado("María", "Torres", 4, false, false);
        listaEmpleados[9] = new Empleado("José", "Díaz", 5, false, false);

    }

    
    public SRMain() {
        salas = new SalaReuniones[4];
        salas[0] = new SalaReuniones("A101", 5);
        salas[1] = new SalaReuniones("B202", 10);
        salas[2] = new SalaReuniones("C303", 15);
        salas[3] = new SalaReuniones("D404", 20);
        iniciarEmpleados();
        initComponents();
        /*/salas[0].reservarsala(listaEmpleados[0], "10", "11");
        salas[1].reservarsala(listaEmpleados[1], "20", "39");
        salas[2].reservarsala(listaEmpleados[2], "20", "39");
        salas[3].reservarsala(listaEmpleados[3], "20", "39");/*/



        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Borde2 = new javax.swing.JPanel();
        searchbar = new javax.swing.JTextField();
        Volver = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        HistorialBTT1 = new javax.swing.JButton();
        ModReservaBTT = new javax.swing.JButton();
        SeleecionarSR = new javax.swing.JTextField();
        Salasddmenu = new javax.swing.JComboBox<>();
        SeleccionarEmp = new javax.swing.JTextField();
        CancelarBTT = new javax.swing.JButton();
        ReservarBTT = new javax.swing.JButton();
        HoraInicioTxt = new javax.swing.JTextField();
        HoraFintxt = new javax.swing.JTextField();
        HoraInicio = new javax.swing.JTextField();
        HoraFin = new javax.swing.JTextField();
        Logo2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        IDEmp = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Borde2.setBackground(new java.awt.Color(153, 0, 0));

        searchbar.setForeground(new java.awt.Color(204, 204, 204));
        searchbar.setText("Buscar");
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });

        Volver.setBackground(new java.awt.Color(153, 0, 0));
        Volver.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        Volver.setForeground(new java.awt.Color(255, 255, 255));
        Volver.setText("Volver");
        Volver.setBorder(null);
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(153, 0, 0));
        jTextField2.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(null);

        HistorialBTT1.setBackground(new java.awt.Color(153, 0, 0));
        HistorialBTT1.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        HistorialBTT1.setForeground(new java.awt.Color(255, 255, 255));
        HistorialBTT1.setText("Historial");
        HistorialBTT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialBTT1ActionPerformed(evt);
            }
        });

        ModReservaBTT.setBackground(new java.awt.Color(153, 0, 0));
        ModReservaBTT.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        ModReservaBTT.setForeground(new java.awt.Color(255, 255, 255));
        ModReservaBTT.setText("Modificar Reserva");
        ModReservaBTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModReservaBTTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Borde2Layout = new javax.swing.GroupLayout(Borde2);
        Borde2.setLayout(Borde2Layout);
        Borde2Layout.setHorizontalGroup(
            Borde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Borde2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Volver)
                .addGap(187, 187, 187)
                .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HistorialBTT1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ModReservaBTT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Borde2Layout.setVerticalGroup(
            Borde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Borde2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Borde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Borde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ModReservaBTT)
                        .addComponent(HistorialBTT1))
                    .addGroup(Borde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Volver)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        SeleecionarSR.setText("Seleccione la Sala de Reuniones:");
        SeleecionarSR.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SeleecionarSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleecionarSRActionPerformed(evt);
            }
        });

        Salasddmenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A101 (5 personas)",
            "B202 (10 personas)",
            "C303 (15 personas)",
            "D404 (20 personas)" }));
Salasddmenu.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        SalasddmenuActionPerformed(evt);
    }
    });

    SeleccionarEmp.setText("ID del Empleado:");
    SeleccionarEmp.setBorder(null);
    SeleccionarEmp.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            SeleccionarEmpActionPerformed(evt);
        }
    });

    CancelarBTT.setBackground(new java.awt.Color(221, 89, 89));
    CancelarBTT.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
    CancelarBTT.setForeground(new java.awt.Color(255, 255, 255));
    CancelarBTT.setText("Cancelar");
    CancelarBTT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    CancelarBTT.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            CancelarBTTMouseClicked(evt);
        }
    });
    CancelarBTT.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            CancelarBTTActionPerformed(evt);
        }
    });

    ReservarBTT.setBackground(new java.awt.Color(221, 89, 89));
    ReservarBTT.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
    ReservarBTT.setForeground(new java.awt.Color(255, 255, 255));
    ReservarBTT.setText("Reservar");
    ReservarBTT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    ReservarBTT.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            ReservarBTTMouseClicked(evt);
        }
    });
    ReservarBTT.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ReservarBTTActionPerformed(evt);
        }
    });

    HoraInicioTxt.setText("Hora de Inicio:");
    HoraInicioTxt.setBorder(null);

    HoraFintxt.setText("Hora de Fin:");
    HoraFintxt.setBorder(null);

    HoraInicio.setForeground(new java.awt.Color(204, 204, 204));
    HoraInicio.setText("hh:mm");
    HoraInicio.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            HoraInicioMousePressed(evt);
        }
    });

    HoraFin.setForeground(new java.awt.Color(204, 204, 204));
    HoraFin.setText("hh:mm");
    HoraFin.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            HoraFinMousePressed(evt);
        }
    });

    Logo2.setEditable(false);
    Logo2.setBackground(new java.awt.Color(255, 255, 255));
    Logo2.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
    Logo2.setText("I N T E L ");
    Logo2.setBorder(null);
    Logo2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    Logo2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            Logo2ActionPerformed(evt);
        }
    });

    jPanel2.setBackground(new java.awt.Color(153, 0, 0));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 39, Short.MAX_VALUE)
    );

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/imagen edifico.png"))); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(Borde2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(SeleecionarSR, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Salasddmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(49, 49, 49))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SeleccionarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HoraInicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HoraFintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(CancelarBTT, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(HoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IDEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(ReservarBTT, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(Logo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(Borde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12)
            .addComponent(Logo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SeleecionarSR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Salasddmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SeleccionarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IDEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HoraInicioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HoraFintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(38, 38, 38)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CancelarBTT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ReservarBTT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(49, 49, 49)))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Logo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logo2ActionPerformed
        Logo2.setEditable(false);
        Logo2.setCaretColor(new java.awt.Color(0, 0, 0, 0));
    }//GEN-LAST:event_Logo2ActionPerformed

    private void SalasddmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalasddmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalasddmenuActionPerformed

    private void SeleccionarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionarEmpActionPerformed

    private void SeleecionarSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleecionarSRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleecionarSRActionPerformed

    private void HoraInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoraInicioMousePressed
        if (HoraInicio.getText().equals("hh:mm")) {
            HoraInicio.setText("");
            HoraInicio.setForeground(Color.BLACK);

        }
        if (String.valueOf(HoraFin.getText()).isEmpty()) {
            HoraFin.setText("hh:mm");
            HoraFin.setForeground(Color.GRAY);
        }


    }//GEN-LAST:event_HoraInicioMousePressed

    private void HoraFinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoraFinMousePressed
        if (String.valueOf(HoraFin.getText()).equals("hh:mm")) {
            HoraFin.setText("");
            HoraFin.setForeground(Color.BLACK);

        }
        if (HoraInicio.getText().isEmpty()) {
            HoraInicio.setText("hh:mm");
            HoraInicio.setForeground(Color.GRAY);
        }


    }//GEN-LAST:event_HoraFinMousePressed

    private void ReservarBTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservarBTTMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this, "\nSala:\n" + Salasddmenu.getSelectedItem() + "\nReservada por:\n" + IDEmp
                + "\nHora Inicio: " + HoraInicio.getText() + "\nHora Fin:" + HoraFin.getText());
        System.exit(0);
    }//GEN-LAST:event_ReservarBTTMouseClicked

    private void CancelarBTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarBTTMouseClicked
        int opcion = JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas cancelar?", "Confirmar Cancelación", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {

            System.out.println("Se canceló la acción.");

        } else {
            System.out.println("La acción no fue cancelada.");
        }
    }//GEN-LAST:event_CancelarBTTMouseClicked

    private void ReservarBTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarBTTActionPerformed
        String opcion = (String) Salasddmenu.getSelectedItem();
        String numeroSala = opcion.substring(0, 4);
        SalaReuniones salaReservar = null;
        Empleado empReserva = null;
        
        //esto es para guardar la sala del jframe en una variable para la reserva
        for (SalaReuniones sala : salas) {
            if (sala.getNumerosala().equals(numeroSala)) {
                salaReservar = sala;
                break;
            }
        }
        if(salaReservar!=null){
            
            try {
                int IDEmp = Integer.parseInt(this.IDEmp.getText());
                for(Empleado emp : listaEmpleados) {
                    if(emp.getId()== IDEmp) {
                        empReserva = emp;
                        break;
                    }
                }
                
            } catch (Exception e) {
            }
            
            
            
            String Hora_Inicio = HoraInicio.getText();
            String Hora_Fin = HoraFin.getText();
            
            boolean reservaexistosa = salaReservar.reservarsala(empReserva, Hora_Inicio, Hora_Fin);
            
            if(reservaexistosa){
                JOptionPane.showMessageDialog(null,  "Reserva realizada con éxito para " + empReserva.getnombrecompleto());


            
            } else{
                JOptionPane.showMessageDialog(null,  "No se pudo realizar la reserva. La sala está ocupada.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                
            }

            
        }else{
            JOptionPane.showMessageDialog(null,"No se encontró ningún empleado con la cédula ingresada.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE );
        }
        
        
    }//GEN-LAST:event_ReservarBTTActionPerformed

    private void CancelarBTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarBTTActionPerformed

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbarActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed

        Menu anterior = new Menu();
        anterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void ModReservaBTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModReservaBTTActionPerformed
         
        
        ModReservaSR Modificar = new ModReservaSR(this);
        Modificar.setVisible(true);
        this.setVisible(false);
        

    }//GEN-LAST:event_ModReservaBTTActionPerformed

    private void HistorialBTT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialBTT1ActionPerformed
        String historial ="Historias de reservas: \n";
        if(salas.length>0){
            for(SalaReuniones sala: salas){
                if(sala.isOcupada()){
                    historial+= sala.mostrarReserva();
                    historial+="\n";
                }
            }
            JOptionPane.showMessageDialog(null, historial);
        }else{
            JOptionPane.showMessageDialog(null, "Ninguna sala ha sido reservada");
        }
        
    }//GEN-LAST:event_HistorialBTT1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SRMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SRMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SRMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SRMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SRMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Borde2;
    private javax.swing.JButton CancelarBTT;
    private javax.swing.JButton HistorialBTT1;
    private javax.swing.JTextField HoraFin;
    private javax.swing.JTextField HoraFintxt;
    private javax.swing.JTextField HoraInicio;
    private javax.swing.JTextField HoraInicioTxt;
    private javax.swing.JTextField IDEmp;
    private javax.swing.JTextField Logo2;
    private javax.swing.JButton ModReservaBTT;
    private javax.swing.JButton ReservarBTT;
    private javax.swing.JComboBox<String> Salasddmenu;
    private javax.swing.JTextField SeleccionarEmp;
    private javax.swing.JTextField SeleecionarSR;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField searchbar;
    // End of variables declaration//GEN-END:variables
}
